spring.application.name=producto-service

#DataSource
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/financiera
spring.datasource.username=root
spring.datasource.password=root

#JPA
spring.jpa.database=MYSQL
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.format_sql=true
spring.jpa.show-sql=true


#Swagger Config
#Configuracion de SpringDoc OpenAPI
springdoc.api-docs.path=/api-docs
#Configuracion de Swagger Interface de usuario
#springdoc.swagger-ui.path=/
springdoc.swagger-ui.enabled=true
#Confguracion para ordernar los endpoints
springdoc.swagger-ui.operationsSorter=alpha
#Configuracion de la informacion de la API
springdoc.open-api.info.title= API PRODUCTOS - SISTEMA FINANCIERA
springdoc.open-api.info.description= API para gestionar productos del sistema financiera
springdoc.open-api.info.version=1.0
springdoc.open-api.info.contact.name=MANUEL HEREDIA UTRILLA
springdoc.open-api.info.contact.email=mherediau@gmail.com
springdoc.open-api.info.contact.url=https://www.linkedin.com/in/manuel-heredia-utrilla-a502611b7/
springdoc.open-api.info.license.name=LICENCIA DE MI API
springdoc.open-api.info.license.url=URL LICENCIA DE MI API
logging.level.org.springframework.web=DEBUG